const darkTheme = {
  "--background-color": "#121212",       // Fond très sombre
  "--text-color": "#e0e0e0",               // Texte en gris clair pour un bon contraste
  "--font-family": "sans-serif",
  "--accent-color": "#bb86fc",             // Accent violet clair, inspiré des thèmes sombres modernes
  "--purple-color": "#8e44ad",
  "--blue-color": "#1e88e5",
  "--green-color": "#43a047",
  "--gray-color": "#616161",
  "--red-text-color": "#cf6679",
  "--decrease-color": "#c0392b",
  "--header-background": "#1f1f1f",        // Header légèrement plus clair que le fond
  "--header-text-color": "#e0e0e0",
  "--header-border-color": "#272727",
  "--title-subtitle-color": "#e0e0e0",
  "--ally-code-input-color": "#bb86fc",
  "--footer-background": "#1f1f1f",        // Footer en harmonie avec le header
  "--footer-text-color": "#e0e0e0",
  "--footer-border-color": "#272727",
  "--scrollbar-track-color": "#e0e0e0",
  "--scrollbar-border-color": "#616161",
  "--scrollbar-thumb-color": "#bb86fc",
  // Les autres variables restent disponibles pour une personnalisation ultérieure
  "--body-background-image": "",
  "--body-background-size": "",
  "--body-text-shadow": "",
  "--nav-button-background": "",
  "--nav-button-border-color": "",
  "--nav-button-text-color": "",
  "--button-background": "",
  "--button-border-color": "",
  "--button-text-color": "",
  "--button-active-border-color": "",
  "--button-red-background": "",
  "--button-red-border-color": "",
  "--button-blue-background": "",
  "--button-blue-border-color": "",
  "--button-blue-text-color": "",
  "--overlay-background-color": "",
  "--modal-background-color": "",
  "--modal-border-color": "",
  "--modal-text-color": "",
  "--modal-flash-h2-color": "",
  "--modal-error-background": "",
  "--modal-error-border-color": "",
  "--modal-error-text-color": "",
  "--mod-detail-border-color": "",
  "--mod-detail-background-color": "",
  "--mod-detail-text-shadow": "",
  "--mod-set-detail-border-color": "",
  "--mod-set-detail-background-color": "",
  "--mod-set-detail-table-th-background": "",
  "--mod-set-detail-table-row-bg-odd": "",
  "--mod-set-detail-table-row-bg-even": "",
  "--mod-set-detail-stat-value-color": "",
  "--mod-image-background-size": "",
  "--mod-icon-atlas-background-size": "",
  "--mod-level-border-color": "",
  "--credits-fill": "",
  "--credits-stroke": "",
  "--credits-stroke-width": "",
  "--dropdown-arrow-color": "",
  "--help-icon-image": "",
  "--help-icon-size": "",
  "--arrow-fill": "",
  "--arrow-stroke": "",
  "--arrow-stroke-width": "",
  "--avatar-border-color": "",
  "--character-edit-form-h3-border-color": "",
  "--character-edit-form-row-bg-odd": "",
  "--character-edit-form-row-text-odd": "",
  "--character-edit-form-row-bg-even": "",
  "--character-edit-form-row-text-even": "",
  "--character-block-border-color": "",
  "--character-block-background": "",
  "--drop-character-box-shadow": "",
  "--mod-filter-option-background": "",
  "--mod-filter-option-border-color": "",
  "--optimizer-view-background-color": "",
  "--pip-size": "",
  "--pip-background-color": "",
  "--slider-input-width": "",
  "--review-background-color": "",
  "--review-heading-color": "",
  "--sidebar-background-color": "",
  "--toggle-sidebar-background-color": "",
  "--toggle-sidebar-border-color": "",
  "--spinner-border-color": "",
  "--spinner-after-border-color": "",
  "--spoiler-border-color": "",
  "--spoiler-title-color": "",
  "--spoiler-divider-color": "",
  "--toggle-switch-background-color": "",
  "--toggle-switch-border-color": "",
  "--toggle-switch-thumb-background-color": "",
  "--warning-label-fill-color": "",
  "--mod-stats-class-S-color": "",
  "--mod-stats-class-A-color": "",
  "--mod-stats-class-B-color": "",
  "--mod-stats-class-C-color": "",
  "--mod-stats-class-D-color": "",
  "--sidebar-child-background-color": "",
  "--sidebar-child-border-color": ""
};

export default darkTheme;
