const redTheme = {
  "--background-color": "#7d1919",       // Fond rouge foncé
  "--text-color": "#ecf0f1",               // Texte clair pour un bon contraste
  "--font-family": "sans-serif",
  "--accent-color": "#e74c3c",             // Accent rouge vif
  "--purple-color": "#9b59b6",
  "--blue-color": "#2980b9",
  "--green-color": "#27ae60",
  "--gray-color": "#bdc3c7",
  "--red-text-color": "#e74c3c",
  "--decrease-color": "#c0392b",
  "--header-background": "#8b1a1a",        // Header en rouge légèrement plus clair
  "--header-text-color": "#ecf0f1",
  "--header-border-color": "#641414",      // Bordure du header en rouge très foncé
  "--title-subtitle-color": "#ecf0f1",
  "--ally-code-input-color": "#e74c3c",
  "--footer-background": "#8b1a1a",        // Footer cohérent avec le header
  "--footer-text-color": "#ecf0f1",
  "--footer-border-color": "#641414",
  "--scrollbar-track-color": "#ecf0f1",
  "--scrollbar-border-color": "#bdc3c7",
  "--scrollbar-thumb-color": "#e74c3c",
  // Les autres variables sont laissées vides pour permettre une personnalisation ultérieure
  "--body-background-image": "",
  "--body-background-size": "",
  "--body-text-shadow": "",
  "--nav-button-background": "",
  "--nav-button-border-color": "",
  "--nav-button-text-color": "",
  "--button-background": "",
  "--button-border-color": "",
  "--button-text-color": "",
  "--button-active-border-color": "",
  "--button-red-background": "",
  "--button-red-border-color": "",
  "--button-blue-background": "",
  "--button-blue-border-color": "",
  "--button-blue-text-color": "",
  "--overlay-background-color": "",
  "--modal-background-color": "",
  "--modal-border-color": "",
  "--modal-text-color": "",
  "--modal-flash-h2-color": "",
  "--modal-error-background": "",
  "--modal-error-border-color": "",
  "--modal-error-text-color": "",
  "--mod-detail-border-color": "",
  "--mod-detail-background-color": "",
  "--mod-detail-text-shadow": "",
  "--mod-set-detail-border-color": "",
  "--mod-set-detail-background-color": "",
  "--mod-set-detail-table-th-background": "",
  "--mod-set-detail-table-row-bg-odd": "",
  "--mod-set-detail-table-row-bg-even": "",
  "--mod-set-detail-stat-value-color": "",
  "--mod-image-background-size": "",
  "--mod-icon-atlas-background-size": "",
  "--mod-level-border-color": "",
  "--credits-fill": "",
  "--credits-stroke": "",
  "--credits-stroke-width": "",
  "--dropdown-arrow-color": "",
  "--help-icon-image": "",
  "--help-icon-size": "",
  "--arrow-fill": "",
  "--arrow-stroke": "",
  "--arrow-stroke-width": "",
  "--avatar-border-color": "",
  "--character-edit-form-h3-border-color": "",
  "--character-edit-form-row-bg-odd": "",
  "--character-edit-form-row-text-odd": "",
  "--character-edit-form-row-bg-even": "",
  "--character-edit-form-row-text-even": "",
  "--character-block-border-color": "",
  "--character-block-background": "",
  "--drop-character-box-shadow": "",
  "--mod-filter-option-background": "",
  "--mod-filter-option-border-color": "",
  "--optimizer-view-background-color": "",
  "--pip-size": "",
  "--pip-background-color": "",
  "--slider-input-width": "",
  "--review-background-color": "",
  "--review-heading-color": "",
  "--sidebar-background-color": "",
  "--toggle-sidebar-background-color": "",
  "--toggle-sidebar-border-color": "",
  "--spinner-border-color": "",
  "--spinner-after-border-color": "",
  "--spoiler-border-color": "",
  "--spoiler-title-color": "",
  "--spoiler-divider-color": "",
  "--toggle-switch-background-color": "",
  "--toggle-switch-border-color": "",
  "--toggle-switch-thumb-background-color": "",
  "--warning-label-fill-color": "",
  "--mod-stats-class-S-color": "",
  "--mod-stats-class-A-color": "",
  "--mod-stats-class-B-color": "",
  "--mod-stats-class-C-color": "",
  "--mod-stats-class-D-color": "",
  "--sidebar-child-background-color": "",
  "--sidebar-child-border-color": ""
};

export default redTheme;
